# Generated by Django 2.2 on 2019-04-21 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_auto_20190420_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_date', '-updated', '-timestamp']},
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='publish_date',
            new_name='published_date',
        ),
    ]
